import { createHash, randomUUID } from 'node:crypto';
import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import { z } from 'zod';
import type { AppConfig } from '../../config/env.js';
import type { PlatformRepository } from '../../core/enterprise-models.js';
import { HttpError } from '../../core/http-error.js';
import { createAuthentication, requireRoles } from '../auth/enterprise-auth.js';
import { CampaignService } from '../campaigns/campaign.service.js';
import { ContentAuthoringService } from '../content/content-authoring.service.js';
import { IntegrationService } from '../integrations/integration.service.js';
import { EnterpriseRiskService } from '../risk-score/enterprise-risk.service.js';
import { SimulationEvaluationStrategyProvider } from '../simulations/simulation-evaluation.strategy.js';

const asyncRoute = (handler: (req: any, res: any) => Promise<unknown>) => (req: any, res: any, next: any) => Promise.resolve(handler(req, res)).catch(next);
const campaignInput = z.object({ name: z.string().min(4).max(120), scenarioVersionId: z.string().uuid(), scheduledAt: z.string().datetime().optional(), sendWindowStart: z.string().optional(), sendWindowEnd: z.string().optional(), department: z.string().optional(), excludedUserIds: z.array(z.string().uuid()).default([]), maxRecipients: z.number().int().min(1).max(2000) });
const eventInput = z.object({ eventType: z.enum(['DELIVERED','BOUNCED','CLICKED','ATTEMPTED_ACTION','REPORTED','IGNORED']), token: z.string().min(24).max(512), idempotencyKey: z.string().min(8).max(128), occurredAt: z.string().datetime().optional(), responseTimeSeconds: z.number().int().nonnegative().max(604800).optional() });

export function createPlatformRouter(repository: PlatformRepository, config: AppConfig) {
  const router = Router(), auth = createAuthentication(repository, config), risk = new EnterpriseRiskService(repository), campaigns = new CampaignService(repository), authoring = new ContentAuthoringService(repository, config), integrations = new IntegrationService(config);

  router.post('/v1/simulation-events', rateLimit({ windowMs: 60_000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false }), asyncRoute(async (req, res) => { const event = eventInput.parse(req.body); const accepted = await repository.recordBehaviorEvent(createHash('sha256').update(event.token).digest('hex'), event.eventType, event.idempotencyKey, event.occurredAt ?? new Date().toISOString(), event.responseTimeSeconds); if (!accepted) throw new HttpError(404, 'Token inválido, vencido o evento duplicado.'); if (['CLICKED','ATTEMPTED_ACTION','REPORTED'].includes(event.eventType)) await risk.calculateAndSave(accepted.companyId, accepted.userId); res.status(202).json({ data: { accepted: true } }); }));
  router.use(auth);

  router.get('/training/modules', asyncRoute(async (req, res) => res.json({ data: await repository.listTrainingModules(req.currentUser.companyId, req.currentUser.id) })));
  router.get('/training/modules/:id', asyncRoute(async (req, res) => { const module = await repository.getTrainingModule(req.currentUser.companyId, req.currentUser.id, req.params.id); if (!module) throw new HttpError(404, 'Módulo no encontrado.'); res.json({ data: module }); }));
  router.patch('/training/progress/:id', asyncRoute(async (req, res) => { const input = z.object({ status: z.enum(['NOT_STARTED','IN_PROGRESS','COMPLETED']), progressPercent: z.number().int().min(0).max(100).optional() }).parse(req.body); const percent = input.status === 'COMPLETED' ? 100 : input.progressPercent ?? (input.status === 'IN_PROGRESS' ? 25 : 0); const progress = await repository.updateTrainingProgress(req.currentUser.companyId, req.currentUser.id, req.params.id, input.status, percent); await risk.calculateAndSave(req.currentUser.companyId, req.currentUser.id); await repository.appendAudit(req.currentUser.companyId, req.currentUser.id, 'training.progress.updated', 'training_module', req.params.id, req.correlationId, { status: input.status, percent }); res.json({ data: progress }); }));

  router.get('/simulations', asyncRoute(async (req, res) => { const items = await repository.listSimulations(req.currentUser.companyId, req.currentUser.id); res.json({ data: items.map(({ correctOptionId: _a, successFeedback: _b, failureFeedback: _c, ...safe }) => safe) }); }));
  router.post('/simulations/:id/answers', asyncRoute(async (req, res) => { const { optionId } = z.object({ optionId: z.string().min(1) }).parse(req.body); const simulation = await repository.getSimulation(req.currentUser.companyId, req.params.id); if (!simulation) throw new HttpError(404, 'Simulación no encontrada.'); const evaluation = SimulationEvaluationStrategyProvider.for(simulation).evaluate(simulation, optionId); const result = { id: randomUUID(), userId: req.currentUser.id, simulationId: simulation.id, selectedOptionId: optionId, ...evaluation, completedAt: new Date().toISOString() }; await repository.saveSimulationResult(req.currentUser.companyId, result); const snapshot = await risk.calculateAndSave(req.currentUser.companyId, req.currentUser.id); res.status(201).json({ data: { ...result, riskSnapshot: snapshot } }); }));
  router.get('/risk-score/me', asyncRoute(async (req, res) => {
    const snapshot = await risk.getOrCalculate(req.currentUser.companyId, req.currentUser.id); const evidence = await repository.getRiskEvidence(req.currentUser.companyId, req.currentUser.id);
    res.json({ data: { ...snapshot, factorContributions: snapshot.factors, factors: { failedSimulations: evidence.simulationResults.filter((item) => !item.wasSuccessful).length, completedModules: evidence.modules.filter((item) => item.status === 'COMPLETED').length, totalModules: (await repository.listTrainingModules(req.currentUser.companyId, req.currentUser.id)).length, repeatedMistakes: Math.max(0, evidence.simulationResults.filter((item) => !item.wasSuccessful).length - 1), reportedThreats: evidence.simulationResults.filter((item) => item.reportedThreat).length + evidence.behaviorEvents.filter((item) => item.eventType === 'REPORTED').length } } });
  }));
  router.get('/v1/risk/users/:id', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => { const user = await repository.findUserById(req.params.id); if (!user || user.companyId !== req.currentUser.companyId) throw new HttpError(404, 'Usuario no encontrado.'); res.json({ data: await risk.getOrCalculate(user.companyId, user.id) }); }));
  router.get('/v1/risk/users/:id/history', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => { const user = await repository.findUserById(req.params.id); if (!user || user.companyId !== req.currentUser.companyId) throw new HttpError(404, 'Usuario no encontrado.'); res.json({ data: await repository.getRiskHistory(user.companyId, user.id, Math.min(Number(req.query.limit ?? 24), 100)) }); }));

  router.get('/v1/scenarios', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => res.json({ data: await campaigns.scenarios(req.currentUser.companyId) })));
  router.get('/v1/campaigns', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => res.json({ data: await campaigns.list(req.currentUser.companyId) })));
  router.post('/v1/campaigns', requireRoles('ADMIN'), asyncRoute(async (req, res) => res.status(201).json({ data: await campaigns.create(req.currentUser.companyId, req.currentUser.id, campaignInput.parse(req.body), req.correlationId) })));
  for (const [path, status] of [['schedule','SCHEDULED'],['pause','PAUSED'],['cancel','CANCELLED']] as const) router.post(`/v1/campaigns/:id/${path}`, requireRoles('ADMIN'), asyncRoute(async (req, res) => res.json({ data: await campaigns.transition(req.currentUser.companyId, req.params.id, status, req.currentUser.id, req.correlationId) })));
  router.get('/v1/campaigns/:id/results', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => { const results = await repository.getCampaignResults(req.currentUser.companyId, req.params.id); if (!results) throw new HttpError(404, 'Campaña no encontrada.'); res.json({ data: results }); }));

  router.get('/v1/analytics/overview', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => { const users = await repository.listUsers(req.currentUser.companyId); const snapshots = await Promise.all(users.map((user) => risk.getOrCalculate(user.companyId, user.id))); const scores = snapshots.map((item) => item.score); const groups = Object.entries(users.reduce<Record<string,string[]>>((acc, user) => { (acc[user.department] ??= []).push(user.id); return acc; }, {})).map(([department, ids]) => ({ department, size: ids.length, suppressed: ids.length < 5, averageRisk: ids.length < 5 ? null : Math.round(snapshots.filter((snapshot) => ids.includes(snapshot.userId)).reduce((sum, item) => sum + item.score, 0) / ids.length) })); res.json({ data: { users: users.length, averageRisk: scores.length ? Math.round(scores.reduce((a,b) => a+b, 0) / scores.length) : 0, highRisk: snapshots.filter((item) => item.level === 'HIGH' && item.confidenceLabel !== 'LOW').length, confidence: { high: snapshots.filter((item) => item.confidenceLabel === 'HIGH').length, low: snapshots.filter((item) => item.confidenceLabel === 'LOW').length }, departments: groups, privacyRule: 'Los grupos menores de cinco personas se ocultan.' } }); }));

  router.get('/v1/content/drafts', requireRoles('SUPERVISOR','ADMIN'), asyncRoute(async (req, res) => res.json({ data: await repository.listContentDrafts(req.currentUser.companyId) })));
  router.post('/v1/content/drafts', requireRoles('ADMIN'), asyncRoute(async (req, res) => res.status(201).json({ data: await authoring.create(req.currentUser.companyId, req.currentUser.id, req.body) })));
  router.post('/v1/content/drafts/:id/approve', requireRoles('ADMIN'), asyncRoute(async (req, res) => { const input = z.object({ decision: z.enum(['APPROVED','REJECTED','CHANGES_REQUESTED']).default('APPROVED'), notes: z.string().max(1000).optional() }).parse(req.body); const draft = await repository.reviewContentDraft(req.currentUser.companyId, req.params.id, req.currentUser.id, input.decision, input.notes); if (!draft) throw new HttpError(404, 'Borrador no encontrado.'); await repository.appendAudit(req.currentUser.companyId, req.currentUser.id, 'content.draft.reviewed', 'content_draft', draft.id, req.correlationId, { decision: input.decision }); res.json({ data: draft }); }));

  router.get('/v1/integrations/status', requireRoles('ADMIN'), (_req, res) => res.json({ data: integrations.statuses() }));
  router.get('/v1/integrations/microsoft/status', requireRoles('ADMIN'), (_req, res) => res.json({ data: integrations.statuses().find((item) => item.provider === 'MICROSOFT_GRAPH') }));
  router.post('/v1/integrations/microsoft/threat-assessments', requireRoles('ADMIN'), asyncRoute(async (req, res) => { const input = z.object({ contentType: z.enum(['mail','url','file']), content: z.string().min(1).max(2_000_000), expectedAssessment: z.enum(['block','unblock']).optional() }).parse(req.body); const result = await integrations.submitThreatAssessment(input); res.status(202).json({ data: result }); }));
  return router;
}
