import { Router } from 'express';
import PDFDocument from 'pdfkit';
import type { Pool } from 'pg';
import type { AppConfig } from '../../config/env.js';
import type { PlatformRepository } from '../../core/enterprise-models.js';
import { createAuthentication, requireRoles } from '../auth/enterprise-auth.js';
import { EnterpriseRiskService } from '../risk-score/enterprise-risk.service.js';

const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
export function createExportRouter(pool: Pool, repository: PlatformRepository, config: AppConfig) {
  const router = Router(), risk = new EnterpriseRiskService(repository); router.use(createAuthentication(repository, config)); router.use(requireRoles('SUPERVISOR','ADMIN'));
  const rows = async (companyId: string) => Promise.all((await repository.listUsers(companyId)).map(async (user) => { const [snapshot, modules] = await Promise.all([risk.getOrCalculate(companyId, user.id), repository.listTrainingModules(companyId, user.id)]); return { user, snapshot, completion: modules.length ? Math.round(modules.filter((item) => item.progress.status === 'COMPLETED').length / modules.length * 100) : 0 }; }));
  router.get('/v1/exports/risk.csv', async (req, res, next) => { try { const data = await rows(req.currentUser!.companyId); const csv = [['Empleado','Email','Departamento','Score','Nivel','Confianza','Versión','Finalización'].map(csvCell).join(','), ...data.map((row) => [row.user.fullName,row.user.email,row.user.department,row.snapshot.score,row.snapshot.level,row.snapshot.confidenceLabel,row.snapshot.scoreVersion,`${row.completion}%`].map(csvCell).join(','))].join('\r\n'); res.type('text/csv').attachment(`cybershield-risk-${new Date().toISOString().slice(0,10)}.csv`).send(`\uFEFF${csv}`); } catch (error) { next(error); } });
  router.get('/v1/exports/risk.pdf', async (req, res, next) => { try { const data = await rows(req.currentUser!.companyId); res.type('application/pdf').attachment(`cybershield-risk-${new Date().toISOString().slice(0,10)}.pdf`); const pdf = new PDFDocument({ margin: 48, info: { Title: 'CyberShield — Reporte de riesgo humano' } }); pdf.pipe(res); pdf.fontSize(20).text('CyberShield — Riesgo humano').fontSize(10).fillColor('#52606d').text(`Generado: ${new Date().toISOString()} · Fórmula HRS-2.0`).moveDown(); for (const row of data) { pdf.fillColor('#111827').fontSize(12).text(`${row.user.fullName} · ${row.user.department}`).fontSize(10).text(`Score ${row.snapshot.score}/100 (${row.snapshot.level}) · confianza ${row.snapshot.confidenceLabel} · formación ${row.completion}%`).moveDown(0.5); if (pdf.y > 720) pdf.addPage(); } pdf.end(); } catch (error) { next(error); } });
  router.get('/v1/siem/events', async (req, res, next) => { try { const since = typeof req.query.since === 'string' ? new Date(req.query.since) : new Date(Date.now() - 7 * 86_400_000); const minSince = new Date(Date.now() - 90 * 86_400_000); const safeSince = Number.isNaN(since.getTime()) || since < minSince ? minSince : since; const result = await pool.query(`SELECT date_trunc('hour',occurred_at) AS bucket,event_type,COUNT(*)::int AS count,COUNT(DISTINCT user_id)::int AS affected_users FROM behavior_events WHERE company_id=$1 AND occurred_at>=$2 GROUP BY bucket,event_type ORDER BY bucket`, [req.currentUser!.companyId, safeSince]); res.json({ data: { generatedAt: new Date().toISOString(), since: safeSince.toISOString(), events: result.rows.map((row) => ({ bucket: row.bucket, eventType: row.event_type, count: row.count, affectedUsers: row.affected_users < 5 ? null : row.affected_users })) } }); } catch (error) { next(error); } });
  return router;
}
