UPDATE companies
SET allowed_email_domains = ARRAY['cybershield.demo'], retention_days = 365
WHERE id = '10000000-0000-4000-8000-000000000001';

UPDATE training_modules SET
  slug = 'phishing-bec', version = 2,
  learning_objectives = '["Verificar remitentes y dominios","Detectar urgencia y cambios de pago","Reportar sin interactuar"]',
  audience_tags = ARRAY['FINANZAS','VENTAS','OPERACIONES','TI'], mitre_technique_ids = ARRAY['T1566.001','T1566.002'],
  sources = '[{"title":"MITRE ATT&CK T1566","url":"https://attack.mitre.org/techniques/T1566/"}]',
  reviewed_at = NOW(), review_due_at = NOW() + INTERVAL '3 months', approved_by = 'CyberShield Security Content Team'
WHERE id = '30000000-0000-4000-8000-000000000001';

UPDATE training_modules SET
  slug = 'passwords-passkeys-mfa', version = 2,
  learning_objectives = '["Usar un gestor de contraseñas","Reconocer MFA fatigue","Adoptar passkeys o MFA resistente al phishing"]',
  audience_tags = ARRAY['FINANZAS','VENTAS','OPERACIONES','TI'], mitre_technique_ids = ARRAY['T1621'],
  sources = '[{"title":"CISA Phishing-Resistant MFA","url":"https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa"}]',
  reviewed_at = NOW(), review_due_at = NOW() + INTERVAL '3 months', approved_by = 'CyberShield Security Content Team'
WHERE id = '30000000-0000-4000-8000-000000000002';

UPDATE training_modules SET
  slug = 'social-engineering-multichannel', version = 2,
  learning_objectives = '["Reconocer pretexting","Verificar por un canal independiente","Proteger códigos y datos internos"]',
  audience_tags = ARRAY['FINANZAS','VENTAS','OPERACIONES','TI'], mitre_technique_ids = ARRAY['T1566.003','T1566.004'],
  sources = '[{"title":"MITRE ATT&CK Phishing","url":"https://attack.mitre.org/techniques/T1566/"}]',
  reviewed_at = NOW(), review_due_at = NOW() + INTERVAL '3 months', approved_by = 'CyberShield Security Content Team'
WHERE id = '30000000-0000-4000-8000-000000000003';

INSERT INTO training_modules(id, title, category, difficulty, estimated_minutes, description, lessons, slug, learning_objectives, audience_tags, mitre_technique_ids, sources, reviewed_at, review_due_at, approved_by)
VALUES
('30000000-0000-4000-8000-000000000004','Consent phishing y recuperación segura','IDENTITY','INTERMEDIATE',8,'Evalúa permisos OAuth, aplicaciones empresariales y flujos de recuperación de cuenta.','[{"title":"Revisa editor y permisos","content":"Una aplicación legítima solicita solo los permisos necesarios."},{"title":"Recuperación segura","content":"Usa canales oficiales y códigos de recuperación protegidos."}]','oauth-consent-recovery','["Identificar permisos OAuth excesivos","Revocar aplicaciones sospechosas","Recuperar cuentas por canales oficiales"]',ARRAY['TI','OPERACIONES'],ARRAY['T1528','T1550'], '[{"title":"MITRE ATT&CK","url":"https://attack.mitre.org/"}]',NOW(),NOW()+INTERVAL '3 months','CyberShield Security Content Team'),
('30000000-0000-4000-8000-000000000005','Fraude financiero y cambio de proveedor','FINANCIAL_FRAUD','INTERMEDIATE',9,'Previene transferencias fraudulentas, cambios bancarios y solicitudes ejecutivas.','[{"title":"Doble verificación","content":"Confirma cambios bancarios con un contacto previamente registrado."},{"title":"Segregación de funciones","content":"Ninguna urgencia elimina la aprobación requerida."}]','financial-vendor-fraud','["Validar cambios de cuenta bancaria","Aplicar doble aprobación","Reconocer BEC financiero"]',ARRAY['FINANZAS','OPERACIONES'],ARRAY['T1566.002'], '[{"title":"MITRE ATT&CK T1566","url":"https://attack.mitre.org/techniques/T1566/"}]',NOW(),NOW()+INTERVAL '3 months','CyberShield Security Content Team'),
('30000000-0000-4000-8000-000000000006','Reporte temprano y respuesta después del clic','INCIDENT_REPORTING','BASIC',6,'Qué reportar, cómo preservar evidencia y qué hacer si ya interactuaste.','[{"title":"Reporta primero","content":"Un reporte temprano permite proteger a otras personas."},{"title":"Después del clic","content":"Desconecta la acción, informa y sigue el protocolo sin ocultar el error."}]','early-reporting-response','["Reportar en menos de cinco minutos","Preservar datos útiles","Actuar sin culpa después de un clic"]',ARRAY['FINANZAS','VENTAS','OPERACIONES','TI'],ARRAY['T1566'], '[{"title":"CISA Phishing Guidance","url":"https://www.cisa.gov/secure-our-world/recognize-and-report-phishing"}]',NOW(),NOW()+INTERVAL '3 months','CyberShield Security Content Team'),
('30000000-0000-4000-8000-000000000007','Trabajo remoto, archivos y terceros','COLLABORATION','BASIC',7,'Protege documentos compartidos, reuniones, proveedores y accesos remotos.','[{"title":"Enlaces compartidos","content":"Verifica propietario, dominio y permisos antes de abrir."},{"title":"Terceros","content":"Limita el acceso al tiempo y alcance necesarios."}]','remote-collaboration-third-parties','["Validar invitaciones externas","Compartir con mínimo privilegio","Reconocer riesgos de terceros"]',ARRAY['VENTAS','OPERACIONES','TI'],ARRAY['T1566.003'], '[{"title":"NIST CSF 2.0","url":"https://www.nist.gov/cyberframework"}]',NOW(),NOW()+INTERVAL '3 months','CyberShield Security Content Team'),
('30000000-0000-4000-8000-000000000008','IA responsable y protección de datos','RESPONSIBLE_AI','INTERMEDIATE',8,'Usa herramientas de IA aprobadas sin exponer información confidencial.','[{"title":"Clasifica antes de pegar","content":"No envíes secretos, datos personales o información contractual a cuentas no aprobadas."},{"title":"Verifica resultados","content":"La salida de IA requiere validación humana y fuentes confiables."}]','responsible-ai-data','["Clasificar datos antes de usar IA","Distinguir herramientas aprobadas","Validar contenido generado"]',ARRAY['FINANZAS','VENTAS','OPERACIONES','TI'],ARRAY[]::TEXT[], '[{"title":"NIST AI RMF","url":"https://www.nist.gov/itl/ai-risk-management-framework"}]',NOW(),NOW()+INTERVAL '3 months','CyberShield Security Content Team')
ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, lessons=EXCLUDED.lessons, slug=EXCLUDED.slug, learning_objectives=EXCLUDED.learning_objectives, audience_tags=EXCLUDED.audience_tags, sources=EXCLUDED.sources, review_due_at=EXCLUDED.review_due_at;

UPDATE simulations SET slug='urgent-invoice', channel='EMAIL', difficulty_score=28, observable_cues='["dominio alterado","urgencia","amenaza de suspensión"]', premise_alignment='HIGH', audience_tags=ARRAY['FINANZAS','OPERACIONES'], mitre_technique_ids=ARRAY['T1566.002'], expected_behavior='Reportar y verificar desde el portal oficial' WHERE id='40000000-0000-4000-8000-000000000001';
UPDATE simulations SET slug='executive-gift-cards', channel='CHAT', difficulty_score=42, observable_cues='["canal externo","confidencialidad","tarjetas de regalo"]', premise_alignment='MEDIUM', audience_tags=ARRAY['VENTAS','OPERACIONES'], mitre_technique_ids=ARRAY['T1566.003'], expected_behavior='Verificar por canal corporativo y reportar' WHERE id='40000000-0000-4000-8000-000000000002';

INSERT INTO simulations(id,title,category,scenario,difficulty,sender,subject,options,correct_option_id,success_feedback,failure_feedback,slug,channel,difficulty_score,observable_cues,premise_alignment,audience_tags,mitre_technique_ids,expected_behavior)
VALUES
('40000000-0000-4000-8000-000000000003','Documento Microsoft 365 compartido','PHISHING','Recibes una invitación a revisar una propuesta desde sharepoint-secure.example.','INTERMEDIATE','Microsoft 365 <sharing@sharepoint-secure.example>','Oliver compartió “Propuesta 2026”','[{"id":"open","label":"Abrir e iniciar sesión"},{"id":"verify","label":"Verificar el dominio y consultar al propietario","reportsThreat":true}]','verify','Detectaste un dominio que imita al servicio real.','Las invitaciones deben validarse por dominio y propietario.','m365-shared-document','EMAIL',65,'["dominio parecido","inicio de sesión externo"]','HIGH',ARRAY['VENTAS','OPERACIONES'],ARRAY['T1566.002'],'Verificar dominio y propietario'),
('40000000-0000-4000-8000-000000000004','Actualización urgente de nómina','PHISHING','Un formulario externo solicita confirmar datos personales para evitar retrasos de nómina.','BASIC','Recursos Humanos <payroll@hr-forms.example>','Confirma tus datos antes de las 3:00 PM','[{"id":"submit","label":"Completar el formulario"},{"id":"report","label":"Reportar y abrir el portal interno","reportsThreat":true}]','report','Usaste el canal interno conocido.','La urgencia y el formulario externo requieren verificación.','payroll-data-request','EMAIL',32,'["formulario externo","fecha límite inesperada"]','HIGH',ARRAY['FINANZAS','OPERACIONES'],ARRAY['T1566.002'],'Reportar y usar el portal interno'),
('40000000-0000-4000-8000-000000000005','Bombardeo MFA y llamada de soporte','SOCIAL_ENGINEERING','Tras varias notificaciones MFA, alguien llama diciendo ser de soporte y pide aprobar la siguiente.','INTERMEDIATE','Mesa de ayuda (llamada externa)','Actividad sospechosa de MFA','[{"id":"approve","label":"Aprobar para detener las alertas"},{"id":"deny","label":"Rechazar, cambiar contraseña y llamar al soporte oficial","reportsThreat":true}]','deny','Interrumpiste el ataque y usaste un contacto confiable.','Soporte nunca debe pedir aprobar una notificación no iniciada.','mfa-fatigue-call','VOICE',72,'["notificaciones no iniciadas","llamada no solicitada"]','HIGH',ARRAY['TI','OPERACIONES'],ARRAY['T1621','T1566.004'],'Rechazar y contactar soporte oficial'),
('40000000-0000-4000-8000-000000000006','Aplicación OAuth de productividad','OAUTH_CONSENT','Una aplicación promete resumir reuniones y solicita leer correo, archivos y contactos de toda la empresa.','INTERMEDIATE','Meeting Genius','Permisos necesarios para continuar','[{"id":"consent","label":"Aceptar todos los permisos"},{"id":"review","label":"Cancelar y solicitar revisión de TI","reportsThreat":true}]','review','Reconociste permisos desproporcionados.','Las aplicaciones deben ser aprobadas y pedir mínimo privilegio.','oauth-excessive-consent','APP',68,'["editor no verificado","permisos amplios"]','MEDIUM',ARRAY['TI','OPERACIONES'],ARRAY['T1528'],'Cancelar y solicitar revisión'),
('40000000-0000-4000-8000-000000000007','Cambio bancario del proveedor','BUSINESS_EMAIL_COMPROMISE','Un proveedor habitual cambia su cuenta bancaria justo antes de una transferencia importante.','INTERMEDIATE','Proveedor habitual <cobros@proveed0r.example>','Nueva cuenta para el pago de hoy','[{"id":"change","label":"Actualizar la cuenta y pagar"},{"id":"callback","label":"Verificar con el contacto registrado y doble aprobación","reportsThreat":true}]','callback','Aplicaste verificación fuera del mensaje.','Los cambios financieros necesitan validación independiente.','vendor-bank-change','EMAIL',76,'["dominio alterado","cambio financiero","urgencia"]','HIGH',ARRAY['FINANZAS'],ARRAY['T1566.002'],'Verificar por contacto registrado'),
('40000000-0000-4000-8000-000000000008','Código solicitado por mesa de ayuda','SOCIAL_ENGINEERING','Una persona con datos internos pide tu código temporal para “reparar la cuenta”.','BASIC','Soporte técnico (llamada)','Código de recuperación','[{"id":"share","label":"Compartir el código"},{"id":"hangup","label":"Finalizar y llamar al número oficial","reportsThreat":true}]','hangup','Protegiste el factor de autenticación.','Los códigos temporales son secretos y no se comparten.','helpdesk-code-request','VOICE',38,'["solicitud de secreto","llamada entrante"]','MEDIUM',ARRAY['TI','OPERACIONES'],ARRAY['T1566.004'],'No compartir y verificar soporte'),
('40000000-0000-4000-8000-000000000009','Mensaje urgente por WhatsApp','SOCIAL_ENGINEERING','Una cuenta nueva con foto del supervisor solicita enviar un reporte confidencial.','BASIC','Supervisor (número desconocido)','Necesito el archivo ahora','[{"id":"send","label":"Enviar el archivo"},{"id":"verify","label":"Verificar en Teams y reportar el número","reportsThreat":true}]','verify','Separaste identidad aparente de identidad verificada.','Las fotos y nombres no prueban identidad.','whatsapp-supervisor','CHAT',35,'["número desconocido","urgencia","datos confidenciales"]','HIGH',ARRAY['VENTAS','OPERACIONES'],ARRAY['T1566.003'],'Verificar por canal corporativo'),
('40000000-0000-4000-8000-000000000010','Invitación externa a reunión','PHISHING','Una invitación externa incluye un enlace acortado y pide instalar un complemento.','INTERMEDIATE','Teams Guest <guest@external-meet.example>','Reunión de proyecto actualizada','[{"id":"install","label":"Instalar el complemento"},{"id":"inspect","label":"Rechazar, inspeccionar y confirmar con el equipo","reportsThreat":true}]','inspect','Evitaste instalar software desde una invitación externa.','Los complementos deben provenir del catálogo aprobado.','external-meeting-invite','EMAIL',58,'["remitente externo","enlace acortado","instalación"]','MEDIUM',ARRAY['VENTAS','TI'],ARRAY['T1566.002','T1566.003'],'Rechazar y confirmar'),
('40000000-0000-4000-8000-000000000011','Paquete retenido con código QR','QR_PHISHING','Un aviso impreso solicita escanear un QR y pagar una tarifa mínima de entrega.','BASIC','Servicio de paquetería','Último intento de entrega','[{"id":"scan","label":"Escanear y pagar"},{"id":"official","label":"Consultar el envío desde la aplicación oficial","reportsThreat":true}]','official','Evitaste trasladar la decisión a un dominio oculto en el QR.','Los códigos QR ocultan el destino hasta abrirlo.','package-qr','QR',40,'["entrega no esperada","pago pequeño","destino oculto"]','MEDIUM',ARRAY['OPERACIONES','VENTAS'],ARRAY['T1566.002'],'Usar la aplicación oficial'),
('40000000-0000-4000-8000-000000000012','Actualización falsa del navegador','SOCIAL_ENGINEERING','Una página muestra “Verifica que eres humano” y pide copiar un comando en PowerShell.','INTERMEDIATE','Página web comprometida','Actualización de seguridad requerida','[{"id":"run","label":"Copiar y ejecutar el comando"},{"id":"close","label":"Cerrar, reportar y actualizar desde el navegador","reportsThreat":true}]','close','Reconociste que una web no debe pedir ejecutar comandos.','Las actualizaciones se instalan desde mecanismos oficiales.','fake-browser-update','WEB',82,'["ejecución de comandos","falsa verificación"]','MEDIUM',ARRAY['TI','OPERACIONES'],ARRAY['T1204.004'],'Cerrar y reportar'),
('40000000-0000-4000-8000-000000000013','Datos confidenciales en IA no aprobada','RESPONSIBLE_AI','Necesitas resumir un contrato y consideras pegarlo en una cuenta personal de IA.','INTERMEDIATE','Escenario interno','Resumen urgente del contrato','[{"id":"paste","label":"Pegar el contrato completo"},{"id":"classify","label":"Clasificar los datos y usar una herramienta aprobada","reportsThreat":true}]','classify','Aplicaste clasificación y control de herramienta.','Las cuentas personales pueden retener información corporativa.','shadow-ai-data','APP',60,'["cuenta personal","documento confidencial"]','HIGH',ARRAY['FINANZAS','VENTAS'],ARRAY[]::TEXT[],'Clasificar y usar herramienta aprobada')
ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title, scenario=EXCLUDED.scenario, options=EXCLUDED.options, correct_option_id=EXCLUDED.correct_option_id, slug=EXCLUDED.slug, difficulty_score=EXCLUDED.difficulty_score, observable_cues=EXCLUDED.observable_cues, premise_alignment=EXCLUDED.premise_alignment, audience_tags=EXCLUDED.audience_tags, expected_behavior=EXCLUDED.expected_behavior;

INSERT INTO scenario_templates(id, company_id, name, category, channel, status, current_version)
SELECT gen_random_uuid(), NULL, s.title, s.category, s.channel, 'PUBLISHED', 1
FROM simulations s
WHERE s.slug IS NOT NULL AND NOT EXISTS (SELECT 1 FROM scenario_templates t WHERE t.name=s.title);

INSERT INTO scenario_versions(template_id, version, subject, sender_name, sender_address, body_html, landing_content, difficulty_score, observable_cues, premise_alignment, audience_tags, mitre_technique_ids, expected_behavior, source_metadata)
SELECT t.id, 1, COALESCE(s.subject,s.title), COALESCE(split_part(s.sender,'<',1),'CyberShield Scenario'), COALESCE(NULLIF(REGEXP_REPLACE(COALESCE(s.sender,''), '.*<|>.*', '', 'g'),''),'simulation@cybershield.demo'), '<p>'||s.scenario||'</p>', jsonb_build_object('scenarioId',s.id,'options',s.options), s.difficulty_score, s.observable_cues, s.premise_alignment, s.audience_tags, s.mitre_technique_ids, COALESCE(s.expected_behavior,'Reportar y verificar'), jsonb_build_object('source','curated','reviewCadence','quarterly')
FROM simulations s JOIN scenario_templates t ON t.name=s.title
WHERE NOT EXISTS (SELECT 1 FROM scenario_versions v WHERE v.template_id=t.id AND v.version=1);
