import { useEffect, useState } from 'react';
import { api } from '../services/api';
import { ErrorState, LoadingState, PageHeader } from '../components/Ui';

type Campaign = { id: string; name: string; scenarioName?: string; status: string; targetCount: number; scheduledAt?: string };
type Scenario = { id: string; templateName: string; difficultyScore: number; channel: string };
type Analytics = { users: number; averageRisk: number; highRisk: number; confidence: { high: number; low: number }; departments: Array<{ department: string; size: number; suppressed: boolean; averageRisk: number | null }>; privacyRule: string };
type Draft = { id: string; title: string; status: string; model?: string; createdAt: string };
type Integration = { provider: string; status: string; scopes: string[] };

export function EnterprisePilotPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]), [scenarios, setScenarios] = useState<Scenario[]>([]), [analytics, setAnalytics] = useState<Analytics | null>(null), [drafts, setDrafts] = useState<Draft[]>([]), [integrations, setIntegrations] = useState<Integration[]>([]);
  const [name, setName] = useState('Piloto trimestral'), [department, setDepartment] = useState(''), [scenarioId, setScenarioId] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const load = () => Promise.all([api.campaigns(), api.scenarios(), api.analytics(), api.contentDrafts(), api.integrations()]).then(([c,s,a,d,i]) => { setCampaigns(c as Campaign[]); setScenarios(s as Scenario[]); setAnalytics(a as Analytics); setDrafts(d as Draft[]); setIntegrations(i as Integration[]); if (!scenarioId && (s as Scenario[])[0]) setScenarioId((s as Scenario[])[0].id); }).catch((reason: Error) => setError(reason.message));
  useEffect(() => { void load(); }, []);
  async function createCampaign() { setBusy(true); setMessage(''); try { await api.createCampaign({ name, scenarioVersionId: scenarioId, department: department || undefined, excludedUserIds: [], maxRecipients: 2000 }); setMessage('Campaña creada en borrador. Revisa audiencia y programa cuando esté lista.'); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function createDraft() { setBusy(true); try { await api.createContentDraft({ industry: 'Servicios profesionales', department: department || 'Finanzas', objective: 'Reconocer urgencia, verificar por un canal independiente y reportar sin interactuar', technique: 'T1566.002', channel: 'EMAIL' }); setMessage('Borrador creado para revisión humana; todavía no está publicado.'); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  if (error) return <ErrorState message={error} />; if (!analytics) return <LoadingState />;
  return <><PageHeader eyebrow="Enterprise Pilot" title="Gestión del riesgo humano" description="Campañas controladas, evidencia explicable, privacidad por cohorte y autoría asistida con revisión humana." />
    <section className="report-summary"><article><span>Personas activas</span><strong>{analytics.users}</strong></article><article><span>Riesgo promedio</span><strong>{analytics.averageRisk}</strong></article><article><span>Riesgo alto confiable</span><strong>{analytics.highRisk}</strong></article><article><span>Confianza alta</span><strong>{analytics.confidence.high}</strong></article></section>
    <section className="admin-overview"><div className="section-title"><div><span className="eyebrow">Campañas</span><h2>Constructor con controles previos</h2></div></div><div className="report-toolbar"><input aria-label="Nombre de campaña" value={name} onChange={(e) => setName(e.target.value)} /><select aria-label="Escenario" value={scenarioId} onChange={(e) => setScenarioId(e.target.value)}>{scenarios.map((s) => <option value={s.id} key={s.id}>{s.templateName} · {s.channel} · {s.difficultyScore}/100</option>)}</select><input aria-label="Departamento opcional" placeholder="Departamento (opcional)" value={department} onChange={(e) => setDepartment(e.target.value)} /><button className="secondary-button" disabled={busy || !scenarioId} onClick={createCampaign}>Crear borrador</button></div>{message && <p className="positive">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Campaña</th><th>Escenario</th><th>Audiencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{campaigns.map((campaign) => <tr key={campaign.id}><td><strong>{campaign.name}</strong></td><td>{campaign.scenarioName}</td><td>{campaign.targetCount}</td><td>{campaign.status}</td><td>{campaign.status === 'DRAFT' && <button className="text-button" onClick={async () => { await api.scheduleCampaign(campaign.id); await load(); }}>Aprobar y programar</button>}</td></tr>)}</tbody></table></div></section>
    <section className="admin-overview"><div className="section-title"><div><span className="eyebrow">Privacidad y confianza</span><h2>Analítica por departamento</h2></div><small>{analytics.privacyRule}</small></div><div className="admin-grid">{analytics.departments.map((item) => <article key={item.department}><span>{item.department} · {item.size} personas</span><strong>{item.suppressed ? 'Oculto' : item.averageRisk}</strong></article>)}</div></section>
    <section className="admin-overview"><div className="section-title"><div><span className="eyebrow">Autoría segura</span><h2>Borradores asistidos</h2></div><button className="secondary-button" disabled={busy} onClick={createDraft}>Generar borrador</button></div><div className="admin-grid">{drafts.slice(0,4).map((draft) => <article key={draft.id}><span>{draft.status} · {draft.model}</span><strong>{draft.title}</strong>{draft.status === 'REVIEW' && <button className="text-button" onClick={async () => { await api.reviewDraft(draft.id, 'APPROVED'); await load(); }}>Aprobar tras revisión</button>}</article>)}</div></section>
    <section className="admin-overview"><div className="section-title"><div><span className="eyebrow">Integraciones</span><h2>Estado de conexiones</h2></div></div><div className="admin-grid">{integrations.map((item) => <article key={item.provider}><span>{item.provider}</span><strong>{item.status}</strong><small>{item.scopes.join(', ')}</small></article>)}</div></section>
  </>;
}
