import { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import type { ReportRow, RiskLevel } from '../types';
import { ErrorState, LoadingState, PageHeader, RiskPill } from '../components/Ui';

export function ReportsPage() {
  const [rows, setRows] = useState<ReportRow[]>([]); const [query, setQuery] = useState(''); const [level, setLevel] = useState<RiskLevel | 'ALL'>('ALL'); const [error, setError] = useState('');
  useEffect(() => { api.reports().then(setRows).catch((reason: Error) => setError(reason.message)); }, []);
  const filtered = useMemo(() => rows.filter((row) => (level === 'ALL' || row.riskLevel === level) && `${row.user.fullName} ${row.user.department}`.toLowerCase().includes(query.toLowerCase())), [rows, query, level]);
  if (error) return <ErrorState message={error} />; if (!rows.length) return <LoadingState />;
  return <><PageHeader eyebrow="Inteligencia organizacional" title="Reporte de riesgo humano" description="Identifica tendencias, prioriza intervenciones y mide el avance de cada empleado." /><section className="report-summary"><article><span>Personas evaluadas</span><strong>{rows.length}</strong></article><article><span>Riesgo alto</span><strong>{rows.filter((row) => row.riskLevel === 'HIGH').length}</strong></article><article><span>Finalización promedio</span><strong>{Math.round(rows.reduce((sum, row) => sum + row.completionPercent, 0) / rows.length)}%</strong></article></section><div className="report-toolbar"><label className="search-box">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar empleado o departamento" /></label><select value={level} onChange={(event) => setLevel(event.target.value as RiskLevel | 'ALL')}><option value="ALL">Todos los niveles</option><option value="HIGH">Riesgo alto</option><option value="MEDIUM">Riesgo medio</option><option value="LOW">Riesgo bajo</option></select></div><div className="table-wrap"><table><thead><tr><th>Empleado</th><th>Progreso</th><th>Fallos</th><th>Cyber Risk Score</th><th>Recomendación</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.user.id}><td><div className="employee-cell"><span className="avatar small">{row.user.fullName[0]}</span><div><strong>{row.user.fullName}</strong><small>{row.user.department}</small></div></div></td><td><strong>{row.completionPercent}%</strong><div className="table-progress"><i style={{ width: `${row.completionPercent}%` }} /></div></td><td>{row.failedSimulations}</td><td><div className="score-cell"><strong>{row.riskScore}</strong><RiskPill level={row.riskLevel} /></div></td><td className="recommendation-cell">{row.recommendations[0]}</td></tr>)}</tbody></table></div></>;
}
