import { useEffect, useState } from 'react';
import { api } from '../services/api';
import type { Simulation, SimulationResult } from '../types';
import { ErrorState, LoadingState, PageHeader } from '../components/Ui';

export function SimulationsPage() {
  const [simulations, setSimulations] = useState<Simulation[]>([]); const [active, setActive] = useState<Simulation | null>(null);
  const [choice, setChoice] = useState(''); const [result, setResult] = useState<SimulationResult | null>(null); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { api.simulations().then(setSimulations).catch((reason: Error) => setError(reason.message)); }, []);
  async function submit() { if (!active || !choice) return; setSubmitting(true); setError(''); try { setResult(await api.submitSimulation(active.id, choice)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible evaluar la respuesta.'); } finally { setSubmitting(false); } }
  function open(simulation: Simulation) { setActive(simulation); setChoice(''); setResult(null); }
  if (error && !simulations.length) return <ErrorState message={error} />; if (!simulations.length) return <LoadingState />;
  if (active) return <><button className="back-button" onClick={() => setActive(null)}>← Volver a simulaciones</button><div className="simulation-layout"><section><span className="eyebrow">Escenario seguro · {active.difficulty}</span><h1>{active.title}</h1><p className="simulation-intro">Analiza cada señal antes de responder. Tu elección actualizará tu perfil de riesgo.</p><div className="message-mock"><div className="message-head"><span className="mail-icon">✉</span><div><strong>{active.subject}</strong><small>De: {active.sender}</small></div><span>Ahora</span></div><p>{active.scenario}</p></div><div className="answer-list"><h2>¿Qué harías?</h2>{active.options.map((option, index) => <label className={choice === option.id ? 'answer selected' : 'answer'} key={option.id}><input type="radio" name="answer" value={option.id} checked={choice === option.id} onChange={() => setChoice(option.id)} disabled={Boolean(result)} /><span className="option-letter">{String.fromCharCode(65 + index)}</span><span>{option.label}</span></label>)}<button className="primary-button" disabled={!choice || submitting || Boolean(result)} onClick={submit}>{submitting ? 'Evaluando…' : 'Confirmar respuesta'}</button></div></section><aside className="simulation-side"><span>Señales a considerar</span><ul><li>¿El canal es corporativo?</li><li>¿Existe presión o urgencia?</li><li>¿Puedes verificar por otra vía?</li></ul>{result && <div className={result.wasSuccessful ? 'feedback success' : 'feedback failure'}><strong>{result.wasSuccessful ? '✓ Respuesta segura' : '! Riesgo detectado'}</strong><p>{result.feedback}</p><small>Tu Cyber Risk Score ya fue actualizado.</small></div>}</aside></div></>;
  return <><PageHeader eyebrow="Laboratorio de amenazas" title="Simulaciones realistas" description="Practica decisiones críticas en un entorno seguro. Los escenarios se adaptan a conductas reales de ataque." /><section className="simulation-cards">{simulations.map((simulation, index) => <article key={simulation.id}><div className={`simulation-art art-${index}`}><span>{index === 0 ? '✉' : '◉'}</span><small>SIMULACIÓN #{String(index + 1).padStart(2, '0')}</small></div><div><span className="card-kicker">{simulation.category.replace('_', ' ')}</span><h2>{simulation.title}</h2><p>{simulation.scenario}</p><div className="simulation-meta"><span>{simulation.difficulty}</span><span>{simulation.attempts ?? 0} intentos</span></div><button className="primary-button full" onClick={() => open(simulation)}>Iniciar escenario →</button></div></article>)}</section></>;
}
